"""add owner_id to courses

Revision ID: 8189800a3336
Revises: 189b84ccfad4
Create Date: 2025-12-25 19:16:12.032526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8189800a3336'
down_revision: Union[str, Sequence[str], None] = '189b84ccfad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['owner_id'], ['id'])
    op.execute("UPDATE courses SET owner_id = 1 WHERE owner_id IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'owner_id')
    # ### end Alembic commands ###
